/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":api"))
    implementation("com.google.code.gson:gson:2.11.0")
}
