/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":api"))
    implementation(project(":gson-impl"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

sourceSets {
    main {
        java {
            srcDir("src/main/java")
            srcDir("../shared-sources/src/main/java")
        }
    }
}
